server:
  port: 8084 #端口
  servlet:
    context-path: /dome #配置项目名
  tomcat:
    uri-encoding: UTF-8

#编码格式（方式一）
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


student:
  name: "燕博博"
  age: 22
