server:
  port: 8086 #端口
#  servlet:
#    context-path: /demo #配置项目名
  tomcat:
    uri-encoding: UTF-8

#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**

#编码格式（方式一）
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  #配置视图重定向jsp文件的位置
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  #配置datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


student:
  name: "燕博博"
  age: 22


